### ISSUE TITLE
Sugestão em loops for

### ISSUE THREAD

**Issue by psergiojr** [Rod1Andrade/LinguagemC#4]
Apenas uma pequena sugestão :wink:

https://github.com/Rod1Andrade/LinguagemC/blob/e61d5f08696673b32f874a8c31050721e86436d4/Listas%20de%20Exercicio/Lista%2013/Exercicio3.c#L87

Nesta linha, em vez de usar `i <= tam-1`, vc pode usar `i < tam`. Essencialmente, é a mesma coisa.
```c
for(int i = 1; i < tam; i++)
```

**Comment by psergiojr** [comment]
Ah, e nas linhas 52 a 62 desse arquivo, tem um merge conflict não-resolvido _(Just in case you missed it :wink: )_

**Comment by Rod1Andrade** [comment]
Muito obrigado pela sugestão. Vou revisar bem o código. (Thanks for the sugestion :smile: )
